import matplotlib.pylab as plt
from utils import coast180
cx,cy=coast180()
cx=cx+360

lt=c3[-knt:]
ln=c4[-knt:]

i1=np.unique(lt)
i0=np.unique(ln)
ni0=len(i0)
ni1=len(i1)
SST=np.reshape(c5[-knt:],[ni0,ni1])
SSS=np.reshape(c6[-knt:],[ni0,ni1])
OHC=np.reshape(c7[-knt:],[ni0,ni1])
mldtc=np.reshape(c9[-knt:],[ni0,ni1])
mlTtc=np.reshape(c10[-knt:],[ni0,ni1])
mlddc=np.reshape(c11[-knt:],[ni0,ni1])
mlTdc=np.reshape(c12[-knt:],[ni0,ni1])
t100=np.reshape(c13[-knt:],[ni0,ni1])
pea=np.reshape(c14[-knt:],[ni0,ni1])

plt.figure(figsize=(12,10))
plt.subplot(331)
plt.contourf(lns,lts,SST*oneq,cmap='Spectral_r'); plt.colorbar()
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.title('(A) SST [C]')
plt.ylabel('latitude [N]')
plt.subplot(332)
plt.contourf(lns,lts,SSS*oneq,cmap='Spectral_r'); plt.colorbar()
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.title('(B) SSS [psu]')
plt.subplot(333)
plt.contourf(lns,lts,OHC*oneq,cmap='Spectral_r'); plt.colorbar()
plt.title('(C) OHC [kJ/cm$^2$]')
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.subplot(334)
plt.contourf(lns,lts,mldtc*oneq,cmap='Spectral_r'); plt.colorbar()
plt.ylabel('latitude [N]')
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.title('(D) MLD$_{Tc}$ [m]')
plt.subplot(335)
plt.contourf(lns,lts,mlddc*oneq,cmap='Spectral_r'); plt.colorbar()
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.title('(E) MLD$_{dc}$ [m]')
plt.subplot(336)
plt.contourf(lns,lts,mlTtc*oneq,cmap='Spectral_r'); plt.colorbar()
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.title('(E) MLT$_{tc}$ [C]')
plt.subplot(337)
plt.contourf(lns,lts,mlTdc*oneq,cmap='Spectral_r'); plt.colorbar()
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.xlabel('lontitude [E]'); plt.ylabel('latitude [N]')
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.title('(F) MLT$_{tc}$ [C]')
plt.subplot(338)
plt.contourf(lns,lts,t100*oneq,cmap='Spectral_r'); plt.colorbar()
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.xlabel('lontitude [E]')
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.title('(G) T100 [C]')
plt.subplot(339)
plt.contourf(lns,lts,pea*oneq,cmap='Spectral_r'); plt.plot(bln,blt,'-ko',markersize=3)
plt.colorbar()
plt.axis([lns.min(),lns.max(),lts.min(),lts.max()])
plt.plot(bln,blt,'-ko',markersize=3); plt.plot(cx,cy,'gray',alpha=0.6)
plt.xlabel('lontitude [E]')
plt.title('(H) PEA [J/m$^3$]')

plt.suptitle('GOFS3.1: \n'+storm.upper()+' forecast hour '+"%03g"%(N*6)+' IC='+cycle,fontsize=13)

plt.savefig('GOGS3p1_isaias_'+cycle+'_f'+"%03g"%(N*6)+'.png',bbox_inches='tight')

