#!/bin/bash
### Job Name
#PBS -N hortense
#PBS -A URTG0024
#PBS -l walltime=11:59:00
#PBS -q economy
### Select 2 nodes with 36 CPUs 
#PBS -l select=2:ncpus=36:mpiprocs=36 
### Send email on abort and end
#PBS -m ae
#PBS -M james.simkins@rutgers.edu

### Run the executable

#------------------------------------------------------------------------------------
# run the code
#------------------------------------------------------------------------------------

source ~/.bashrc

conda activate gridtools

python /glade/work/jsimkins/runs-MOM6/nwa25/hurrhortense.py 19960906.ocean_hourly.nc 19960906.ocean_static.nc

